karafka/waterdrop

CHANGELOG.md
Gemfile.lock
README.md
lib/water_drop/aspects/formatter.rb
lib/water_drop/version.rb
spec/lib/water_drop/aspects/formatter_spec.rb

Aspect to json

---

Rakefile

@mensfeld Please review. It is small update to rake file. Should I change version?

Remove unnecessary gem_tasks; Fix dev tools gem name.

---

CHANGELOG.md
README.md
lib/water_drop/config.rb
lib/water_drop/message.rb
lib/water_drop/producer_proxy.rb
spec/lib/water_drop/config_spec.rb
spec/lib/water_drop/producer_proxy_spec.rb

Adds the following configuration options:
```
kafka.ssl.ca_cert
kafka.ssl.client_cert
kafka.ssl.client_cert_key
```
(Also fixed some misc typos)
Please let me know if I'm missing anything!
@mensfeld @jpcaissy

Add ssl capabilities

---

README.md

This PR changes the build badges to SVG for sharper readability ✨

README: Build badge with SVG

---

Gemfile
Gemfile.lock
config/errors.yml
lib/water_drop/config.rb
lib/water_drop/schemas/config.rb

uses dry-v from master for now

dry-validation 1.0.0 updates

---

lib/water_drop/contracts/config.rb

Refs dry-rb/dry-validation#566

Fix handling of keys in kafka_scope_rule

---

CHANGELOG.md
Gemfile.lock
README.md
lib/water_drop/producer/builder.rb
lib/water_drop/producer/statistics_decorator.rb
spec/lib/water_drop/producer/statistics_decorator_spec.rb

Since some of the rdkafka metrics are absolute, this code calculates the diff against the previously published stats.
close https://github.com/karafka/waterdrop/pull/118

better stats reporting

---

lib/water_drop/producer/async.rb
lib/water_drop/producer/buffer.rb
lib/water_drop/producer/sync.rb

close https://github.com/karafka/waterdrop/issues/124

2.7.0 kwarg depr fixes

---

.github/FUNDING.yml
CHANGELOG.md
Gemfile.lock
README.md
lib/water_drop/config.rb
lib/water_drop/version.rb
waterdrop.gemspec

Bumps dependencies and removes deprec warnings.

gem bump and small readme updates

---

CHANGELOG.md
Gemfile.lock
lib/water_drop/instrumentation/callbacks_manager.rb
lib/water_drop/version.rb
spec/lib/water_drop/instrumentation/callbacks_manager_spec.rb
spec/lib/water_drop/producer_spec.rb

close https://github.com/karafka/waterdrop/issues/218

#218 - callbacks manager concurrency fix

---

waterdrop.gemspec

ref https://github.com/karafka/karafka/issues/764

mfa requirement

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/patches/rdkafka/producer.rb
lib/waterdrop/version.rb

close https://github.com/karafka/waterdrop/issues/244

align patches with naming from rdkafka

---

CHANGELOG.md

Release changelog update

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/instrumentation/vendors/datadog/listener.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/instrumentation/vendors/datadog/listener_spec.rb

Small refactor of the DataDog/Statsd listener to align for future extraction to `karafka-common`.

small dd/statsd code refactor

---

lib/waterdrop/config.rb
lib/waterdrop/instrumentation/vendors/datadog/listener.rb

fix yard reference

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/contracts/message.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/contracts/message_spec.rb
spec/lib/waterdrop/producer/async_spec.rb

close https://github.com/karafka/waterdrop/issues/267

Allow sending tombstone messages

---

CHANGELOG.md

v2.4.2 release

---

CHANGELOG.md
lib/waterdrop/config.rb

replace uuid id with hex

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb

close https://github.com/karafka/waterdrop/issues/301

Remove logger listener empty debug info

---

waterdrop.gemspec

close https://github.com/karafka/karafka/issues/1101

#1101 Align gem metadata to match the rest of the ecosystem

---

CHANGELOG.md
Gemfile.lock
README.md
lib/waterdrop/config.rb
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/support/factories/producer.rb

close https://github.com/karafka/waterdrop/issues/333

Support buffer overflow retry

---

README.md
spec/lib/waterdrop/producer_spec.rb
spec/support/factories/producer.rb

One more spec to cover idempotent producer setup and basic usage.

Spec with docs updates

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop.rb
lib/waterdrop/version.rb

close https://github.com/karafka/waterdrop/issues/345

v2.5.2 with pathame fix

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/errors.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/async.rb
lib/waterdrop/producer/sync.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb

close https://github.com/karafka/waterdrop/issues/367

Improve error reporting - include underlying error details in the error message

---

lib/waterdrop/producer/async.rb
lib/waterdrop/producer/sync.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb

Fix for https://github.com/karafka/waterdrop/issues/370

Add cause to the errors that are passed into instrumentation

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/version.rb

Just a bump of WaterDrop version to accommodate changes.

WaterDrop bump to 2.6.5

---

docker-compose.yml
spec/lib/waterdrop/instrumentation/vendors/datadog/metrics_listener_spec.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb

Switching docker to KRaft mode so we don't rely on zookeeper which has a tendency to hang.

Switch to KRaft

---

docker-compose.yml

ref https://github.com/karafka/karafka/issues/1636

rename docker kafka cluster id

---

lib/waterdrop/producer.rb
lib/waterdrop/producer/async.rb
lib/waterdrop/producer/sync.rb
lib/waterdrop/producer/transactions.rb
spec/lib/waterdrop/producer/transactions_spec.rb

This PR enhances the transactions. It provides support for transactional production without explicit transaction usage which simplifies the code and provides full backward compatibility, so transactions can be enabled without any code changes.

Support auto transactions

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer_spec.rb

close https://github.com/karafka/waterdrop/issues/444

expose partition_count for custom partitioners

---

lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb
spec/lib/waterdrop/instrumentation/notifications_spec.rb

close https://github.com/karafka/waterdrop/issues/450

instrument producer lifecycle events

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/config.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/sync.rb
lib/waterdrop/producer/transactions.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/sync_spec.rb
spec/support/factories/producer.rb

close https://github.com/karafka/waterdrop/issues/332
close https://github.com/karafka/waterdrop/issues/456

change defaults

---

Gemfile.lock
lib/waterdrop/config.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/transactions_spec.rb

close https://github.com/karafka/waterdrop/issues/465

align defaults so they can work with transactional producer out of the box

---

CHANGELOG.md
Gemfile.lock
config/locales/errors.yml
lib/waterdrop/clients/rdkafka.rb
lib/waterdrop/config.rb
lib/waterdrop/contracts/config.rb
lib/waterdrop/instrumentation/callbacks/oauthbearer_token_refresh.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/contracts/config_spec.rb
spec/lib/waterdrop/instrumentation/callbacks/oauthbearer_token_refresh_spec.rb
spec/lib/waterdrop/producer_spec.rb
waterdrop.gemspec

waterdrop part of https://github.com/karafka/karafka/issues/1767
additionally I added extra specs that were missing and missing config rules.

Support custom oauth bearer

---

CHANGELOG.md
lib/waterdrop/producer.rb
lib/waterdrop/producer/buffer.rb
spec/lib/waterdrop/producer/buffer_spec.rb

close https://github.com/karafka/waterdrop/issues/474

fix double middleware and double checks

---

lib/waterdrop/producer/variant.rb

This seems to be needed now but I have tracked down _why_ yet.

Add delegate requirement

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/variant_spec.rb

close https://github.com/karafka/waterdrop/issues/487

Alias `with` with `variant`

---

CHANGELOG.md
lib/waterdrop/producer.rb
spec/lib/waterdrop/config_spec.rb
spec/lib/waterdrop/producer_spec.rb
spec/support/factories/producer.rb

close https://github.com/karafka/waterdrop/issues/489

add idempotent? flag

---

CHANGELOG.md
config/locales/errors.yml
lib/waterdrop/contracts/variant.rb
lib/waterdrop/producer/variant.rb
spec/lib/waterdrop/contracts/variant_spec.rb
spec/lib/waterdrop/producer/variant_spec.rb

close https://github.com/karafka/waterdrop/issues/491

ensure acks cannot be altered when idempotent

---

CHANGELOG.md
lib/waterdrop/errors.rb
lib/waterdrop/producer/transactions.rb
spec/lib/waterdrop/errors_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb

close https://github.com/karafka/waterdrop/issues/511

fix early return dangling state

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/errors.rb
lib/waterdrop/producer/transactions.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/clients/buffered_spec.rb
spec/lib/waterdrop/clients/dummy_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb

close https://github.com/karafka/waterdrop/issues/513

Replace throw API with raise WaterDrop::AbortTransaction

---

CHANGELOG.md
lib/waterdrop/producer.rb
lib/waterdrop/producer/sync.rb
spec/lib/waterdrop/producer/transactions_spec.rb
spec/support/factories/producer.rb

transactional part of https://github.com/karafka/waterdrop/issues/518

normalize dispatched for transactional

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR adds issue templates to tackle cases where users would provide incomplete or problematic bug reports.

use templates similar to karafka

---

.github/workflows/ci.yml

ref https://github.com/karafka/karafka/issues/2371

use ruby 3.4 as default

---

CHANGELOG.md
lib/waterdrop/errors.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/transactions.rb
spec/lib/waterdrop/producer/transactions_spec.rb

close https://github.com/karafka/waterdrop/issues/549

improve transactional locking

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer_spec.rb

close https://github.com/karafka/waterdrop/issues/554

support producers tagging

---

.github/workflows/ci.yml
bin/verify_kafka_warnings
waterdrop.gemspec

ref https://github.com/karafka/karafka/issues/2358

Add post-execution kafka warnings checks

---

.github/workflows/ci.yml
CHANGELOG.md
Gemfile.lock
bin/verify_topics_naming
lib/waterdrop/version.rb

ref https://github.com/karafka/karafka/issues/2454

verify test topics naming convention in the CI

---

CHANGELOG.md
Gemfile
Gemfile.lock
spec/lib/waterdrop/instrumentation/callbacks/delivery_spec.rb
spec/lib/waterdrop/instrumentation/vendors/datadog/metrics_listener_spec.rb
spec/lib/waterdrop/producer/buffer_spec.rb
spec/lib/waterdrop/producer_spec.rb
spec/spec_helper.rb
spec/support/factories.rb
spec/support/factories/message.rb
spec/support/factories/producer.rb
spec/support/rspec_locator.rb

Stabilizes a spec and bumps deps.
i also removed factory bot and activesupport. The rspec locator is replaced from core until this is done in core: https://github.com/karafka/karafka-core/issues/160

Stabilize spec +remove activesupport + remove factory bot

---

.github/CODEOWNERS
.github/workflows/ci.yml
.github/workflows/verify-action-pins.yml
renovate.json

part of https://github.com/karafka/karafka/issues/2481

harden workflows

---

CHANGELOG.md
Gemfile.lock
spec/lib/waterdrop/producer/async_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb
spec/support/factories/message.rb
waterdrop.gemspec

close https://github.com/karafka/waterdrop/issues/586

add kip-82 specs

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/version.rb

ref https://github.com/karafka/karafka/issues/2677

normalize logs
