karafka/waterdrop

lib/water_drop/aspects/after_aspect.rb
lib/water_drop/aspects/around_aspect.rb
spec/lib/water_drop/aspects/after_aspect_spec.rb
spec/lib/water_drop/aspects/around_aspect_spec.rb

WaterDrop::Aspects::AfterAspect.apply(
Calculator,
method: :sum,
topic: 'karafka_topic_aspect',
message: ->(result) { result }
)
class Calculator
def sum(a, b)
a + b
end
end
Calculator.new.sum(4,5) # should return 9, now it returns true/false (whether message was sent)

Around and After aspects should return result of function call.

---

Gemfile.lock
lib/water_drop/config.rb
lib/water_drop/producer_proxy.rb
spec/lib/water_drop/config_spec.rb
spec/lib/water_drop/producer_proxy_spec.rb
waterdrop.gemspec

Required to support Heroku Kafka ca cert rotation. See: https://devcenter.heroku.com/changelog-items/1197

support ruby-kafka 0.4.0 `ssl_ca_cert_file_path` option

---

README.md
lib/water_drop/config.rb
lib/water_drop/producer_proxy.rb
spec/lib/water_drop/config_spec.rb
spec/lib/water_drop/producer_proxy_spec.rb

We'd like to leverage `ruby-kafka`'s built in compression. This change will not introduce any backward incompatibility since it sets defaults to not enabling compression.

added producer compression

---

.gitignore
Gemfile
Gemfile.lock
config/errors.yml
lib/water_drop.rb
lib/water_drop/base_producer.rb
lib/water_drop/config.rb
lib/water_drop/config_applier.rb
lib/water_drop/errors.rb
lib/water_drop/instrumentation/monitor.rb
lib/water_drop/schemas/config.rb
lib/water_drop/schemas/message_options.rb
spec/lib/water_drop/schemas/config_spec.rb
spec/lib/water_drop_spec.rb
spec/spec_helper.rb
waterdrop.gemspec

This PR:
- adds the `sasl_oauth_token_provider` support
- removes the production dependency on the null logger by using the stdout logger as default with warn and setting the file as a target for running specs
- fixes some typos
This way of handling logger is much better: there won't be a case when someone unexperienced does an integration and sees nothing when running.

api sync, typos fixes and null-logger removal

---

lib/water_drop/config.rb
lib/water_drop/contracts/config.rb
spec/lib/water_drop/contracts/config_spec.rb

maintains parity with karafka 1.3.0, which already supports configuring `ssl_verify_hostname` 
When we try to upgrade to karafka 1.3.0, our application cannot connect to Kafka in Heroku to publish messages.
See following PRs for additional context:
https://github.com/zendesk/ruby-kafka/pull/733
https://github.com/karafka/karafka/pull/512

Expose setting to optionally verify hostname on ssl certs

---

config/errors.yml
lib/water_drop/contracts/config.rb
spec/lib/water_drop/config_spec.rb
spec/lib/water_drop/contracts/config_spec.rb

Solves https://github.com/karafka/waterdrop/issues/113
`dry` wasn't really cooperative with a dot in the attribute name ("bootstrap.servers") and `rule(kafka: "bootstrap.servers")` was raising an error about defining a rule for a non-existent attribute which probably conflicts with a dot notation used for nesting in dry. To avoid some transformations on a config hash, I simply defined the rule for `kafka` attribute itself. A bit ugly, but does the job :P

validate bootstrap.servers format

---

lib/water_drop/producer.rb
lib/water_drop/producer/buffer.rb
spec/lib/water_drop/producer_spec.rb

This PR fixes the concurrency problem that could occur when:
- 1 thread would be setting up configuration while another would try to fetch a client (crazy but possible)
- 1 thread would try to close the producer and another would try to do the same (librdkafka crashes in that case)
- after fork: 1 thread would try to set a client and another one would try to do the same when pid is already set BUT the client is not
close https://github.com/karafka/waterdrop/issues/138

make client fetching and closing thread safe

---

lib/water_drop/sync_producer.rb
spec/lib/water_drop/async_producer_spec.rb
spec/lib/water_drop/sync_producer_spec.rb
spec/spec_helper.rb

Pass `options` as kwargs from SyncProducer to DeliveryBoy

---

CHANGELOG.md
lib/water_drop/producer.rb

This PR uses producer id to bind the finalizer, that way we do not reference it in the definition, skipping the warning. It does not change how and when it kicks in.

fix binded finalizer warning

---

CHANGELOG.md
lib/water_drop/producer.rb
spec/lib/water_drop/producer/async_spec.rb
spec/lib/water_drop/producer/buffer_spec.rb
spec/lib/water_drop/producer/builder_spec.rb
spec/lib/water_drop/producer/sync_spec.rb
spec/lib/water_drop/producer_spec.rb

This PR closes all the producers prior to VM closing. This should ensure we do not have any weird segmentation faults as things are done the correct way.

Close producers in specs

---

CHANGELOG.md
lib/water_drop/producer.rb
spec/lib/water_drop/producer_spec.rb

This PR optimizes closing process. When producer was not used, connection to Kafka was not established via client. If so, there is no need to close it.

do not close never used client

---

CHANGELOG.md
Gemfile.lock
lib/water_drop/version.rb

- minimum version of ruby-kafka is now 1.3
- update gems requirements in the gemspec (nijikon)

1.4.4 release

---

CHANGELOG.md

- Fixes an issue where multiple producers would emit stats of other producers causing the same stats to be published several times (as many times as a number of producers). This could cause invalid reporting for multi-kafka setups.
- Fixes a bug where emitted statistics would contain their first value as the first delta value for first stats emitted.
- Fixes a bug where decorated statistics would include a delta for a root field with non-numeric values.
- Introduces support for error callbacks instrumentation notifications with `error.emitted` monitor emitted key for tracking background errors that would occur on the producer (disconnects, etc).
- Removes the `:producer` key from `statistics.emitted` and replaces it with `:producer_id` not to inject whole producer into the payload
- …

v2.0.5 release

---

CHANGELOG.md
Gemfile.lock
lib/water_drop/instrumentation/callbacks/error.rb
lib/water_drop/instrumentation/stdout_listener.rb
lib/water_drop/producer.rb
lib/water_drop/producer/async.rb
lib/water_drop/producer/buffer.rb
lib/water_drop/producer/sync.rb
lib/water_drop/version.rb
spec/lib/water_drop/instrumentation/stdout_listener_spec.rb
spec/support/factories/producer.rb

This PR:
- Replaces `:producer` with `:producer_id` in events and update `StdoutListener` accordingly. This change aligns all the events in terms of not publishing the whole producer object in the events here and in Karafka 2.0.
- Add `error.emitted` into the `StdoutListener` tracking.
- Enable `StdoutLogger` in specs for additional integration coverage.

Normalize events keys and update StdoutListener 

---

CHANGELOG.md
Gemfile.lock
README.md
lib/water_drop/instrumentation/callbacks/error.rb
lib/water_drop/instrumentation/monitor.rb
lib/water_drop/instrumentation/stdout_listener.rb
lib/water_drop/producer/buffer.rb
lib/water_drop/version.rb
spec/lib/water_drop/instrumentation/callbacks/error_spec.rb
spec/lib/water_drop/instrumentation/stdout_listener_spec.rb
spec/lib/water_drop/producer_spec.rb

This PR normalizes how we handle errors by emitting all of the errors into a single error notification channel / key `error.occurred`.
This change will allow us to:
- Will drastically simplify error handling as we won't have to track particular keys and support many of them. Instead we can just setup a listener and all errors will be reported.
- Propagate the same approach to Karafka and use a single error handle key across the framework
This will allow us to add new places where we report errors (if needed) and all the customers will be able to handle that out of the box without any code changes. It is much better for error notification than a granular engine.
In case someone needs a granular error detection, then can be done both based on the `type` key in the event as well as on the …

Unify error publisher keys to a single key

---

CHANGELOG.md
lib/water_drop/config.rb
lib/water_drop/contracts/base.rb
lib/water_drop/contracts/config.rb
lib/water_drop/contracts/message.rb
lib/water_drop/producer.rb
spec/lib/water_drop/contracts/base_spec.rb

This PR introduces a common base for contracts to align with incoming Karafka changes and a `#validate!` method as we always use validation in a raise-immediately way. No external APIs are impacted.

introduce a common contract base

---

CHANGELOG.md
waterdrop.gemspec

We are officially dropping support for ruby 2.6 because maintenance ends beginning of April 2022. More information in this post https://www.ruby-lang.org/en/news/2021/11/24/ruby-2-6-9-released/. We also can't support JRuby because it is currently based on ruby 2.6.

drop support for ruby 2.6

---

CHANGELOG.md
README.md
config/errors.yml
lib/waterdrop/config.rb
lib/waterdrop/contracts/config.rb
spec/lib/waterdrop/config_spec.rb
spec/lib/waterdrop/contracts/config_spec.rb
spec/lib/waterdrop/instrumentation/vendors/datadog/listener_spec.rb
spec/lib/waterdrop/producer/builder_spec.rb
spec/lib/waterdrop/producer_spec.rb
spec/support/factories/producer.rb

This PR ensures, that when defining Kafka settings, all are symbols. That way there won't a case where there is an accidental conflict or mistake.

ensure kafka keys are symbolized

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/patches/rdkafka/producer.rb
spec/spec_helper.rb

This PR adds changes needed to support rdkafka 0.13.beta1 and higher while remaining compatibility with previous versions.

Support changes in rdkafka 0.13

---

CHANGELOG.md
lib/waterdrop/patches/rdkafka/metadata.rb

There is a case where the metadata request times out. We need to implement a cache on top but this will mitigate the problem occurring in rdkafka itself.

retry metadata requests upon timeout

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/patches/rdkafka/metadata.rb
lib/waterdrop/patches/rdkafka/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/patches/rdkafka/metadata_spec.rb
spec/lib/waterdrop/patches/rdkafka/producer_spec.rb

This PR:
- fixes the error catching visibility scope that was broken
- introduces a 30 second TTL cache on partition count so upon `partition_key` usage, we do not have to query kafka over and over again.

Introduce partition count cache and improve retries

---

CHANGELOG.md
Gemfile.lock
README.md
lib/waterdrop/config.rb
lib/waterdrop/version.rb

This change comes as users' expectation of having sane defaults that allow for most of the "normal" things to work and align with future karafka changes and future web-ui.
If anyone has a different setting, it will not be overwritten. If someone is not using metrics at all, this is one JSON parse every 5 seconds so should not put a huge stress on the system.

Emit metrics by default every 5 seconds

---

CHANGELOG.md
Gemfile.lock
README.md
lib/waterdrop/config.rb
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/middleware.rb
lib/waterdrop/patches/rdkafka/metadata.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/async.rb
lib/waterdrop/producer/buffer.rb
lib/waterdrop/producer/sync.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/middleware_spec.rb
spec/lib/waterdrop/producer/async_spec.rb

This PR:
- adds support for pre-validation and pre-dispatch middleware
- adds support for missing leader retry on metadata

Publishing middleware support

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/patches/rdkafka/producer.rb
waterdrop.gemspec

This PR delegates the time methods to `Karafka::Core::Helpers::Time` to align with karafka and web.

Use time from core

---

CHANGELOG.md
waterdrop.gemspec

same as here: https://github.com/karafka/karafka/pull/1263

rely on version lock from core

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/instrumentation/callbacks/error.rb
lib/waterdrop/producer/buffer.rb
lib/waterdrop/version.rb

This PR adds the caller key to error instrumentation, so the API is aligned with Karafka.

Include caller in the instrumentation calls

---

CHANGELOG.md
lib/waterdrop/instrumentation/notifications.rb

small change to allow ppl to rebind the events onto an alternative notifications bus

Allow for notifications events list programmatic access

---

CHANGELOG.md
Gemfile.lock
README.md
lib/waterdrop/errors.rb
lib/waterdrop/instrumentation/callbacks/delivery.rb
lib/waterdrop/instrumentation/callbacks/error.rb
lib/waterdrop/patches/rdkafka/client.rb
lib/waterdrop/patches/rdkafka/producer.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/async.rb
lib/waterdrop/producer/buffer.rb
lib/waterdrop/producer/sync.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/errors_spec.rb
spec/lib/waterdrop/instrumentation/callbacks/delivery_spec.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/lib/waterdrop/producer/buffer_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb
spec/support/factories/producer.rb

This PR does several things (taken from readme):
- Pipe delivery errors that occurred not via the error callback using the `error.occurred` channel.
- Pipe **all** the errors including synchronous errors via the `error.occurred`.
- Remove the `WaterDrop::Errors::FlushFailureError` in favour of correct error that occurred to unify the error handling.
- Introduce `WaterDrop::Errors::ProduceError` and `WaterDrop::Errors::ProduceManyError` for any inline raised errors that occur. You can get the original error by using the `#cause`.
- Do **not** flush when there is no data to flush in the internal buffer.
close https://github.com/karafka/waterdrop/issues/322

Pipe delivery errors coming from reports via notifications

---

CHANGELOG.md
Gemfile.lock
README.md
config/locales/errors.yml
lib/waterdrop/config.rb
lib/waterdrop/contracts/config.rb
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/contracts/config_spec.rb
spec/lib/waterdrop/producer/async_spec.rb
spec/support/factories/producer.rb

This PR fixes few confusing inconsistencies:
- renames `wait_on_queue_full_timeout` to `wait_on_queue_full_backoff` to reflect what it does. 
- uses `wait_on_queue_full_timeout` correctly, that is to measure the total with retries
- fixes the `type` on error to indicate appropriate caller
- adds missing config validations
alongside:
close https://github.com/karafka/waterdrop/issues/351
close https://github.com/karafka/waterdrop/issues/335

improve queue backoffs

---

lib/waterdrop/testing.rb
lib/waterdrop/testing/spec_kafka_client.rb
spec/lib/waterdrop/testing/spec_kafka_client_spec.rb
spec/lib/waterdrop/testing_spec.rb

Add a helper client to use in tests to monitor produced messages.
It is based on [the similar class](https://github.com/karafka/karafka-testing/blob/master/lib/karafka/testing/spec_producer_client.rb) from `karafka-testing` but is simplified and is aimed for producer-only apps.

Add WaterDrop::Testing::SpecKafkaClient

---

CHANGELOG.md
Gemfile.lock
README.md
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb

Mitigates the issue when especially in Rails the logger debug level reports extensively whole messages content.
close https://github.com/karafka/waterdrop/issues/375

allow for disabling of extensive messages logging in the logger listener

---

CHANGELOG.md
Gemfile
Gemfile.lock
lib/waterdrop/clients/rdkafka.rb
lib/waterdrop/config.rb
lib/waterdrop/contracts/message.rb
lib/waterdrop/errors.rb
lib/waterdrop/instrumentation/callbacks/delivery.rb
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer.rb
lib/waterdrop/producer/transactions.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/contracts/message_spec.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb
spec/lib/waterdrop/producer/sync_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb
spec/lib/waterdrop/producer_spec.rb
spec/support/factories/producer.rb
waterdrop.gemspec

close https://github.com/karafka/waterdrop/issues/393
close https://github.com/karafka/waterdrop/issues/382
close https://github.com/karafka/waterdrop/issues/243

`#purge`, `#close!` and `#transaction`

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer/transactions.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/transactions_spec.rb

This PR fixes the below issue and also makes sure we abort transaction on all errors including criticals.
close https://github.com/karafka/waterdrop/issues/399

handle critical errors

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/clients/rdkafka.rb
lib/waterdrop/instrumentation/callbacks/delivery.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/instrumentation/callbacks/delivery_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb

close https://github.com/karafka/waterdrop/issues/402
backwards compatible.

Purge flow for transactions

---

config/locales/errors.yml
lib/waterdrop/contracts/transactional_offset.rb
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer/transactions.rb
spec/lib/waterdrop/clients/buffered_spec.rb
spec/lib/waterdrop/contracts/transactional_offset_spec.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb

While working on it during the weekend in karafka I noticed that this API actually resembles more rdkafka API rather than high-levle karafka API. This changes that.
Not a breaking change since transcational exactly once semantics API was not released yet. That way our transactional and regular marking as consumed in karafka can have aligned API expectation.

align transactional api

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/config.rb
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/producer/async_spec.rb

close https://github.com/karafka/waterdrop/issues/457

Introduce `instrument_on_wait_queue_full` for ability to disable instrumentation on non-critical queue full errors

---

CHANGELOG.md
Gemfile.lock
config/locales/errors.yml
lib/waterdrop/config.rb
lib/waterdrop/contracts/config.rb
lib/waterdrop/producer.rb
lib/waterdrop/version.rb
spec/lib/waterdrop/contracts/config_spec.rb

This PR removes the warnings coming from changes in rdkafka-ruby and bumps alpha release.

upgrade warnings from rdkafka

---

lib/waterdrop/instrumentation/vendors/datadog/metrics_listener.rb

According to rdkafka documentation (https://karafka.io/docs/Librdkafka-Statistics/#brokers) this is already a gauge, and doesn't need to be diffed like the cumulative stats do. This is supported by our observations--in our application this metric is frequently negative.

Treat the queue size as a gauge rather than a cumulative stat

---

lib/waterdrop/instrumentation/vendors/datadog/metrics_listener.rb
spec/lib/waterdrop/instrumentation/vendors/datadog/metrics_listener_spec.rb

Librdkafka emits topic level stats like so:
```
{
"name": "rdkafka#producer-1",
"client_id": "rdkafka",
"ts": 5016483227792,
"brokers": {},
"topics": {
"test": {
"topic": "test",
"batchsize": {},
"batchcnt": {},
"partitions": {}
}
}
},
}
```
This update allows users to subscribe to topic level stats as a metric with:
`RdKafkaMetric.new(:gauge, :topics, 'topics.batchcnt.avg', %w[batchcnt avg])`
Related issue: https://github.com/karafka/waterdrop/issues/495

Add topic scope to report_metric

---

CHANGELOG.md
config/locales/errors.yml
lib/waterdrop/config.rb
lib/waterdrop/contracts/config.rb
lib/waterdrop/instrumentation/logger_listener.rb
lib/waterdrop/instrumentation/notifications.rb
lib/waterdrop/producer/transactions.rb
spec/lib/waterdrop/contracts/config_spec.rb
spec/lib/waterdrop/instrumentation/logger_listener_spec.rb
spec/lib/waterdrop/producer/transactions_spec.rb

This PR introduces the ability of the producer to reload its underlying client when in transactional mode. This allows us to deal with cases when something goes wrong and a given instance should not be used.
Since it is used only from inside locked transactions, this does not have race conditions.
Fencing is excluded to prevent some weird race conditions.
close https://github.com/karafka/waterdrop/issues/501

Introduce `reload_on_transaction_fatal_error` to reload the librdkafka after transactional failures

---

CHANGELOG.md
lib/waterdrop/instrumentation/logger_listener.rb

it was pointed to me that having a super-microsecond precision makes no sense and I agree.
before:
```
[waterdrop-915b81c89ffe] Async producing of 1 messages to 1 topics took 0.09454702043533325 ms
```
after:
```
[waterdrop-915b81c89ffe] Async producing of 1 messages to 1 topics took 0.09 ms
```
the same will be done in karafka.

limit ms logger resolution

---

.github/workflows/ci.yml
README.md

We're slowly removing 3.0 support as planned.

remove 3.0 from CI

---

CHANGELOG.md
Gemfile.lock
waterdrop.gemspec

Per our EOL policy, Ruby 3.0 is soon going to go down. There is no point in releasing breaking release without this change.

Require ruby 3.1

---

spec/lib/waterdrop/producer/transactions_spec.rb

without this sleep it may be that the dispatch from waterdrop is not happening fast enough and no purge is needed

stabilize spec

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/version.rb
spec/lib/waterdrop/producer_spec.rb
waterdrop.gemspec

This PR makes the master dependent on `0.20.0.rc1` so we can test things out and then align specs and expectations against new rdkafka.

use karafka-rdkafka 0.20.0

---

CHANGELOG.md
Gemfile.lock
lib/waterdrop/version.rb
waterdrop.gemspec

Due to partition cache count engine replacement, this sets the minimum value to utilize it and aligns with karafka

use karafka-rdkafka 0.19.2.rc1

---

lib/waterdrop/producer.rb

It may be that a client has explicitly set `enable.idempotence` to false, so checking of the key is set may lead to false positives.
In practice this led to a `VariantInvalidError` because a variant was trying to override `required.acks` for a producer that had explicitly set `enable.idempotence` to false.

A producer is not idempotent unless the enable.idempotence config is true
